apiVersion: v1
kind: Secret
metadata:
  name: es-exporter-secret
  namespace: aom-middleware-demo
type: Opaque
data:
  esURI: http://10.247.43.50:9200  #you-guess  #对应 ElasticSearch 的 URI

--
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: elasticsearch-exporter # 根据业务需要调整成对应的名称，建议加上 Redis 实例的信息
  name: elasticsearch-exporter # 根据业务需要调整成对应的名称，建议加上 Redis 实例的信息
  namespace: aom-middleware-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: elasticsearch-exporter # 根据业务需要调整成对应的名称，建议加上 Redis 实例的信息
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-exporter # 根据业务需要调整成对应的名称，建议加上 Redis 实例的信息
    spec:
      containers:
        - name: elasticsearch-exporter
          env:
            - name: ES_ALL
              value: "true"
            - name: ES_URI
              valueFrom:
                secretKeyRef:
                  name: es-exporter-secret
                  key: esURI
          image: swr.cn-east-3.myhuaweicloud.com/aom-org/bitnami/elasticsearch-exporter:1.5.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9114
              name: metric-port  # 这个名称在配置抓取任务的时候需要
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          securityContext:
            privileged: false
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: default-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
# 通过PodMonitor采集数据到AOM
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: elasticsearch-exporter
  namespace: aom-middleware-demo
spec:
  namespaceSelector:
    matchNames:
      - aom-middleware-demo
  podMetricsEndpoints:
  - interval: 30s
    path: /metrics
    port: metric-port
  selector:
    matchLabels:
      k8s-app: elasticsearch-exporter