apiVersion: v1
kind: Secret
metadata:
  name: memcached-exporter-secret
  namespace: aom-middleware-demo
type: Opaque
data:
  memcachedURI: 10.247.167.43:11211  #you-guess  #对应 Memcached 的 URI

--
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: memcached-exporter # 根据业务需要调整成对应的名称，建议加上 Redis 实例的信息
  name: memcached-exporter # 根据业务需要调整成对应的名称，建议加上 Redis 实例的信息
  namespace: aom-middleware-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: memcached-exporter # 根据业务需要调整成对应的名称，建议加上 Redis 实例的信息
  template:
    metadata:
      labels:
        k8s-app: memcached-exporter # 根据业务需要调整成对应的名称，建议加上 Redis 实例的信息
    spec:
      containers:
        - name: memcached-exporter
          env:
            - name: Memcached_Url
              valueFrom:
                secretKeyRef:
                  name: memcached-exporter-secret
                  key: memcachedURI
          command: ["memcached_exporter", "--memcached.address=$(Memcached_Url)"]
          image: swr.cn-east-3.myhuaweicloud.com/aom-org/bitnami/memcached-exporter:0.13.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9150
              name: metric-port  # 这个名称在配置抓取任务的时候需要
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          securityContext:
            privileged: false
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: default-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
# 通过PodMonitor采集数据到AOM
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: memcached-exporter
  namespace: aom-middleware-demo
spec:
  namespaceSelector:
    matchNames:
      - aom-middleware-demo
  podMetricsEndpoints:
  - interval: 30s
    path: /metrics
    port: metric-port
  selector:
    matchLabels:
      k8s-app: memcached-exporter