apiVersion: v1
kind: Secret
metadata:
  name: nginx-prometheus-secret
  namespace: aom-middleware-demo
type: Opaque
data:
  consulURI: http://10.247.199.75:8080/nginx_status  #you-guess  #对应 consul 的 URI

--
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: nginx-prometheus-exporter # 根据业务需要调整成对应的名称，建议加上 Redis 实例的信息
  name: nginx-prometheus-exporter # 根据业务需要调整成对应的名称，建议加上 Redis 实例的信息
  namespace: aom-middleware-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nginx-prometheus-exporter # 根据业务需要调整成对应的名称，建议加上 Redis 实例的信息
  template:
    metadata:
      labels:
        k8s-app: nginx-prometheus-exporter # 根据业务需要调整成对应的名称，建议加上 Redis 实例的信息
    spec:
      containers:
        - name: nginx-prometheus-exporter
          env:
            - name: Nginx_Url
              valueFrom:
                secretKeyRef:
                  name: nginx-prometheus-exporter-secret
                  key: nginxURI
          command: ["nginx-prometheus-exporter", "-nginx.scrape-uri=$(Nginx_Url)"]
          image: swr.cn-east-3.myhuaweicloud.com/aom-org/nginx/nginx-prometheus-exporter:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9113
              name: metric-port  # 这个名称在配置抓取任务的时候需要
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          securityContext:
            privileged: false
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: default-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
# 通过PodMonitor采集数据到AOM
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nginx-prometheus-exporter
  namespace: aom-middleware-demo
spec:
  namespaceSelector:
    matchNames:
      - aom-middleware-demo
  podMetricsEndpoints:
  - interval: 30s
    path: /metrics
    port: metric-port
  selector:
    matchLabels:
      k8s-app: nginx-prometheus-exporter