apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-evs-redis-6379
  namespace: my-space
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "csi-disk"  # 这里指定storageClass名称