apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-evs-redis-6379
  namespace: my-space
spec:
  volumeName: pv-evs-redis-6379
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: "csi-disk"  # 这里指定storageClass名称